### ISSUE TITLE
computer_objects_path unable to see objects in active directory

### ISSUE THREAD

**Issue by unix-bomber** [Thulium-Drake/ansible-role-adjoin#1]
In  ansible-role-adjoin/defaults/main.yml on line 45, if the computer_objects_path option is present, the role fails with

"["Failed to join domain: failed to precreate account in ou ou=SomeOU,ou=Computers,dc=SomeDC,dc=EXAMPLE,dc=GOV: No such object"]}"

Despite object existing in AD

Removing computer_objects_path allows role to complete successfully.

**Comment by unix-bomber** [comment]
Your role rocks 👍

**Comment by Thulium-Drake** [comment]
Hmm, that is interesting. That variable is used to allow for creating the Computer objects in a different OU then OU=Computers,DC=example,DC=com (which is the default for AD). Do note btw, you have to write the path as ```Computers/someOU```

And in my current tests I also use this variable and it seems to work :)

Test scenario: https://github.com/Thulium-Drake/ansible-role-adjoin/blob/master/molecule/default/playbook.yml
Result: https://drone.element-networks.nl/Element-Networks/ansible-role-adjoin/103

**Comment by unix-bomber** [comment]
Rodger that - I'm using RHEL 7.7 with latest updates.

      ldap_base_dn: 'DC=domain,DC=forest,DC=gov',
      computer_objects_path: 'Computers/Servers',

is what I have in defaults. I'll chalk it up to one of the packages on my system being broken.

Thank you!

**Comment by Thulium-Drake** [comment]
If the OU does not exist, you could get this error, in that case, it'd be best to just set 'Computers'

The default values are meant to be used more as an example, as no 2 AD's are alike :)

**Comment by unix-bomber** [comment]
Yep, gotcha there. I'm not using the default OU of 'someou' that you have as a placeholder. I have to sanitize the configs from my environment. Even when using the default 'Computers' OU it doesn't work. From doing some digging, it looks like the most recent version of samba/smb is to blame

**Comment by Thulium-Drake** [comment]
Were you able to work out the issues with Samba?
