### ISSUE TITLE
Unable to debug error in "Include OS specific vars" step due to no_log

### ISSUE THREAD

**Issue by PavelPikat** [Thulium-Drake/ansible-role-adjoin#3]
Hi

When executing the role, I'm getting an error

```
TASK [thulium_drake.adjoin : Include OS specific vars] *************************
Wednesday 02 December 2020  17:39:21 +0000 (0:00:00.073)       0:04:52.354 **** 
fatal: [ansible-eu1-dev-1]: FAILED! => 
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
```

Any suggestions on how no_log within the role can be disabled?
Can you maybe use adjoin_nolog varible for that task like in all other tasks?

**Comment by PavelPikat** [comment]
I ended up copying the entire role's source code to my local environment and switching the `no_log` to `false` just to realize I had facts gathering disabled, so `ansible_os_family` was undefined.

**Comment by Thulium-Drake** [comment]
I have updated that task to listen to ```adjoin_no_log``` as well :-)
